name 'sonos'
maintainer 'Marcin Sawicki'
maintainer_email 'odcinek@gmail.com'
license 'Apache 2.0'
description 'Installs and configures Plex media server'
version '0.0.1'
supports 'ubuntu'
supports 'fedora'
supports 'centos'
